version: "3.8"

services:
  backend:
    build: ./backend
    container_name: codemify-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/products.json:/app/products.json
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped
    networks:
      - codemify-network

  frontend:
    build: ./frontend
    container_name: codemify-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - codemify-network

networks:
  codemify-network:
    driver: bridge
